version: '3'
services:
  web: # uwsgi
    container_name: app_web_enviame
    build:
      context: .
      dockerfile: Dockerfile
    image: enviame/ubuntu
    networks:
      - backend
    ports:
      - "0.0.0.0:${WEB_HTTP_PORT}:8000"
      - "8101:84" #  proxy -> backend
      - "8102:8081" # backend = django
    volumes:
      - ./backend:/app
      - ./bin:/usr/local/scripts
      - ./nginx:/nginx
      - ./media:/app_media
    # restart: always
    depends_on:
      - db
    tty: true
  db:
    image: postgres
    container_name: postgres_enviame
    networks:
      - backend
    volumes:
      - ./bin:/usr/local/scripts
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # restart: always
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:5432"
    command:
      -c fsync=off

networks:
  backend:
      driver: bridge
