# Generated by Django 2.2.19 on 2021-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('estado', models.CharField(choices=[('-1', 'Inactivo'), ('1', 'Activo')], default='1', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('dv', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('year_constitution', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
